image:
  file: .gitpod.Dockerfile

tasks:
  # This "CLI - Testnet" task opens a terminal for you to interact with the
  # testnet network.
  - name: CLI - Testnet
    # We specify some required environment variables for use on the testnet.
    env:
      # This can be set by the user, but this terminal is dedicated to testnet so set for convenience.
      SOROBAN_RPC_URL: "https://soroban-testnet.stellar.org"
      SOROBAN_NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
    # To keep things tidy, we clear the terminal from the previous output.
    command: |
      clear
  - name: CLI - Sandbox
    init: |
      make all
    command: |
      gp open README.md
      gp open increment/src/lib.rs
      gp open increment/src/test.rs
      gp open README.md
      stellar version
vscode:
  extensions:
    - rust-lang.rust-analyzer
    - vadimcn.vscode-lldb

ports:
  # This port is open for "Something with cargo test I think"??
  - port: 4226
    visibility: private
    onOpen: ignore
