tasks:
  - init: |
      mkdir -p ~/.local/bin
      curl -L https://github.com/stellar/soroban-cli/releases/download/v0.1.2/soroban-cli-0.1.2-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/.local/bin soroban
      rustup update
      cargo install --locked sccache
  - command: |
      cargo build --target wasm32-unknown-unknown --profile release
      soroban invoke --id 1 --wasm target/wasm32-unknown-unknown/release/soroban_increment_contract.wasm --fn increment

vscode:
  extensions:
    - matklad.rust-analyzer
    - vadimcn.vscode-lldb

github:
  prebuilds:
    addBadge: true
