image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cargo fetch
      make build test
    command: |
      gp ports await 23000
      gp open README.md
      gp open increment/src/lib.rs
      gp open increment/src/test.rs
      gp open README.md
      make build test
      soroban invoke --id 1 --wasm target/wasm32-unknown-unknown/release/soroban_increment_contract.wasm --fn increment

vscode:
  extensions:
    - matklad.rust-analyzer
    - vadimcn.vscode-lldb

github:
  prebuilds:
    addBadge: true
    addComment: true
    pullRequests: true
    pullRequestsFromForks: true
