tasks:
  - init: |
      mkdir -p ~/.local/bin
      curl -L https://github.com/stellar/soroban-cli/releases/download/v0.1.2/soroban-cli-0.1.2-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/.local/bin soroban
      curl -L https://github.com/mozilla/sccache/releases/download/v0.3.0/sccache-v0.3.0-x86_64-unknown-linux-musl.tar.gz | tar xz -C ~/.local/bin sccache
      rustup update
      rustup install nightly
      rustup target add --toolchain nightly wasm32-unknown-unknown
      rustup component add --toolchain nightly rust-src
      sudo apt-get update
      sudo apt-get install -y binaryen
      docker pull stellar/quickstart:soroban-dev
      cargo fetch
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 2G
    command: |
      code increment/src/lib.rs
      cargo build --target wasm32-unknown-unknown --profile release
      soroban invoke --id 1 --wasm target/wasm32-unknown-unknown/release/soroban_increment_contract.wasm --fn increment

vscode:
  extensions:
    - matklad.rust-analyzer
    - vadimcn.vscode-lldb

github:
  prebuilds:
    addBadge: true
    addComment: true
    pullRequests: true
    pullRequestsFromForks: true
