[workspace]
resolver = "2"

members = [
    "authorization",
    "hello_world",
    "increment",
    "custom_types",
    "cross_contract/contract_a",
    "cross_contract/contract_b",
    "deployer/contract",
    "deployer/deployer",
    "liquidity_pool",
    "liquidity_pool_router",
    "single_offer",
    "single_offer_xfer_from",
    "single_offer_router",
    "events",
    "timelock",
    "token",
    "token_with_payload",
    "liquidity_pool_router_with_payload"
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[patch.crates-io]
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "3b299468" }
soroban-spec = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "3b299468" }
soroban-auth = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "3b299468" }
soroban-sdk-macros = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "3b299468" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "5d57d88" }
soroban-env-guest = { git = "https://github.com/stellar/rs-soroban-env", rev = "5d57d88" }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "5d57d88" }
soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "5d57d88" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "5d57d88" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "469efc9" }
wasmi = { package = "soroban-wasmi", git = "https://github.com/stellar/wasmi", rev = "a61b6df" }
