[workspace]
resolver = "2"

members = [
    "hello_world",
    "increment",
    "auth",
    "auth_advanced",
    "custom_types",
    "cross_contract/contract_a",
    "cross_contract/contract_b",
    "deployer/contract",
    "deployer/deployer",
    "liquidity_pool",
    "liquidity_pool_router",
    "single_offer",
    "single_offer_xfer_from",
    "single_offer_router",
    "events",
    "timelock",
    "token",
    "logging",
    "errors",
    "wallet",
]

[profile.release-with-logs]
inherits = "release"
debug-assertions = true

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# [patch.crates-io]
# soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "3ec51a3d" }
# soroban-spec = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "3ec51a3d" }
# soroban-auth = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "3ec51a3d" }
# soroban-sdk-macros = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "3ec51a3d" }
# soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "c04c2332" }
# soroban-env-guest = { git = "https://github.com/stellar/rs-soroban-env", rev = "c04c2332" }
# soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "c04c2332" }
# soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "c04c2332" }
# soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "c04c2332" }
# stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "e88f9fa7" }
# wasmi = { package = "soroban-wasmi", git = "https://github.com/stellar/wasmi", rev = "d1ec0036" }
