[package]
name = "soroban-auth-contract"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "0.2.0"

[dev_dependencies]
soroban-sdk = { version = "0.2.0", features = ["testutils"] }
